# Change these first
owner: Obi-Wana # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aither Web - HTTPS
    url: https://aither.cc
    icon: https://aither.cc/favicon.ico
  - name: Aither Chat - IRC
    check: "tcp-ping"
    url: irc.aither.cc
    icon: https://cdn-icons-png.flaticon.com/512/309/309666.png
    port: 6697

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  theme: night
  introTitle: "**Aither Status**"
  introMessage: Service Uptime powered by[Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
